// Authored neighborhood plans: activity counts never move streets or buildings.
const site = (
  id,
  role,
  x,
  z,
  roadZ,
  side,
  model,
  height,
  maxWidth,
  maxDepth,
  extra = {},
) => ({
  id,
  role,
  x,
  z,
  roadZ,
  side,
  model,
  height,
  maxWidth,
  maxDepth,
  ...extra,
});

export const DISTRICT_LAYOUTS = {
  1: {
    x: -60,
    z: 0,
    bounds: { left: -140, right: 20, top: -70, bottom: 70 },
    polygon: [
      { x: -120, z: -70 },
      { x: 0, z: -64 },
      { x: 20, z: -42 },
      { x: 20, z: 52 },
      { x: -2, z: 70 },
      { x: -120, z: 66 },
      { x: -140, z: 48 },
      { x: -140, z: -48 },
    ],
    roadZ: 0,
    loop: { left: -122, right: 2, top: -42, bottom: 54 },
    localRoads: [
      [-122, -42, 2, -42],
      [-122, 0, 20, 0],
      [-122, 54, 2, 54],
      [-122, -42, -122, 54],
      [-60, -42, -60, 54],
      [2, -42, 2, 54],
      [-60, 28, 2, 28],
    ],
    localTour: [
      { x: -122, z: 0 },
      { x: -122, z: -42 },
      { x: 2, z: -42 },
      { x: 2, z: 54 },
      { x: -122, z: 54 },
      { x: -122, z: 0 },
    ],
    gate: { x: 20, z: 0, side: "east", outward: { x: 1, z: 0 } },
    bay: { x: 15, z: -9 },
    walkBay: { x: 15, z: -13 },
    station: { x: -76, z: 42, stairDirection: -1 },
    sites: [
      site(
        "eth-finance",
        "integrator",
        -104,
        -55,
        -42,
        -1,
        "building-skyscraper-b",
        16,
        11,
        9,
        { slot: 0 },
      ),
      site(
        "eth-exchange",
        "integrator",
        -16,
        -55,
        -42,
        -1,
        "building-j",
        9,
        13,
        9,
        { slot: 1 },
      ),
      site(
        "eth-market",
        "integrator",
        -104,
        -12.5,
        0,
        -1,
        "building-g",
        11,
        10,
        8,
        { slot: 2 },
      ),
      site(
        "eth-tower",
        "integrator",
        -16,
        -12.5,
        0,
        -1,
        "building-skyscraper-c",
        14,
        10,
        8,
        { slot: 3 },
      ),
      site(
        "eth-campus",
        "integrator",
        -16,
        15,
        28,
        -1,
        "building-e",
        6,
        13,
        9,
        { slot: 4 },
      ),
      site(
        "eth-home-origin",
        "relay",
        -106,
        14,
        0,
        1,
        "building-type-a",
        4.6,
        6,
        5.8,
        { endpoint: "origin" },
      ),
      site(
        "eth-home-destination",
        "relay",
        -42,
        16,
        28,
        -1,
        "building-type-c",
        4.1,
        6,
        5.8,
        { endpoint: "destination" },
      ),
      site(
        "eth-west-home",
        "scenery",
        -87,
        -55,
        -42,
        -1,
        "building-type-b",
        3.8,
        6,
        5.8,
      ),
      site(
        "eth-garden-home",
        "scenery",
        -72,
        -55,
        -42,
        -1,
        "building-type-a",
        4.4,
        6,
        5.8,
      ),
      site(
        "eth-north-home",
        "scenery",
        -108,
        -27,
        -42,
        1,
        "building-type-c",
        4,
        6,
        5.8,
      ),
      site(
        "eth-east-home",
        "scenery",
        -8,
        -27,
        -42,
        1,
        "building-type-b",
        3.7,
        6,
        5.8,
      ),
      site("eth-commons", "commons", -82, 14, 0, 1, "building-c", 5, 8, 6),
      site("eth-shop-row", "scenery", -94, -28, -42, 1, "building-h", 7, 8, 7),
      site(
        "eth-corner-shop",
        "scenery",
        -87,
        -10,
        0,
        -1,
        "building-e",
        5.5,
        9,
        6,
      ),
      site(
        "eth-office-row",
        "scenery",
        -72,
        -9.5,
        0,
        -1,
        "building-d",
        8,
        7,
        6,
      ),
      site(
        "eth-courtyard-home",
        "scenery",
        -91,
        14,
        0,
        1,
        "building-type-c",
        4,
        6,
        5,
      ),
      site("eth-civic-block", "scenery", -72, 15, 0, 1, "building-f", 10, 7, 8),
      site(
        "eth-community-hall",
        "scenery",
        -79,
        30,
        54,
        -1,
        "building-j",
        8,
        19,
        11,
      ),
      site(
        "eth-north-block",
        "scenery",
        -45,
        -54,
        -42,
        -1,
        "building-j",
        8,
        17,
        9,
      ),
      site(
        "eth-east-offices",
        "scenery",
        -46,
        -11,
        0,
        -1,
        "building-b",
        9,
        12,
        8,
      ),
      site(
        "eth-east-shops",
        "scenery",
        -31,
        -12,
        0,
        -1,
        "building-e",
        6,
        11,
        8,
      ),
      site(
        "eth-south-home-a",
        "scenery",
        -108,
        63,
        54,
        1,
        "building-type-a",
        3,
        6,
        4,
      ),
      site(
        "eth-south-home-b",
        "scenery",
        -89,
        63,
        54,
        1,
        "building-type-b",
        3,
        6,
        4,
      ),
      site(
        "eth-south-home-c",
        "scenery",
        -40,
        63,
        54,
        1,
        "building-type-c",
        3,
        6,
        4,
      ),
      site("eth-police", "police", 13, 16, 0, 1, "building-a", 4.5, 5.5, 6),
    ],
    parks: [
      {
        x: -78,
        z: -23,
        width: 19,
        depth: 17,
        trees: [
          { x: -82, z: -25, size: 4.3 },
          { x: -74, z: -20, size: 3.8 },
        ],
      },
      {
        x: -106,
        z: 30,
        width: 22,
        depth: 12,
        trees: [
          { x: -113, z: 29, size: 3.7 },
          { x: -99, z: 31, size: 4.2 },
        ],
      },
      {
        x: -33,
        z: -28,
        width: 17,
        depth: 16,
        trees: [
          { x: -35, z: -31, size: 4.1 },
          { x: -29, z: -25, size: 3.6 },
        ],
      },
    ],
  },
  8453: {
    x: 109,
    z: 0,
    bounds: { left: 68, right: 150, top: -36, bottom: 54 },
    polygon: [
      { x: 78, z: -36 },
      { x: 137, z: -36 },
      { x: 150, z: -24 },
      { x: 150, z: 40 },
      { x: 136, z: 54 },
      { x: 80, z: 54 },
      { x: 68, z: 39 },
      { x: 68, z: -24 },
    ],
    roadZ: 0,
    loop: { left: 80, right: 138, top: -20, bottom: 12 },
    localRoads: [
      [80, -20, 138, -20],
      [80, 12, 138, 12],
      [80, -20, 80, 12],
      [138, -20, 138, 12],
      [68, 0, 109, 0],
      [109, -20, 109, 0],
    ],
    localTour: [
      { x: 80, z: 0 },
      { x: 80, z: -20 },
      { x: 138, z: -20 },
      { x: 138, z: 12 },
      { x: 80, z: 12 },
      { x: 80, z: 0 },
    ],
    gate: { x: 68, z: 0, side: "west", outward: { x: -1, z: 0 } },
    bay: { x: 73, z: -9 },
    walkBay: { x: 73, z: -13 },
    station: { x: 109, z: 42, stairDirection: 1 },
    sites: [
      site(
        "base-workshop",
        "integrator",
        123,
        -31.3,
        -20,
        -1,
        "building-i",
        7,
        9,
        6,
        { slot: 0 },
      ),
      site(
        "base-home-origin",
        "relay",
        94,
        -11.3,
        0,
        -1,
        "building-type-b",
        3.7,
        5.8,
        5.4,
        { endpoint: "origin" },
      ),
      site(
        "base-home-destination",
        "relay",
        120,
        24,
        12,
        1,
        "building-type-c",
        4.2,
        6,
        5.6,
        { endpoint: "destination" },
      ),
      site(
        "base-garden-home",
        "scenery",
        89,
        24,
        12,
        1,
        "building-type-a",
        3.8,
        6,
        5.6,
      ),
      site(
        "base-commons",
        "commons",
        91,
        -31.3,
        -20,
        -1,
        "building-c",
        4.3,
        7,
        6,
      ),
      site("base-police", "police", 133, 24, 12, 1, "building-a", 4.4, 5.5, 6),
    ],
    parks: [
      {
        x: 126,
        z: -5,
        width: 15,
        depth: 11,
        trees: [
          { x: 122, z: -5, size: 3.2 },
          { x: 130, z: -4, size: 3.8 },
        ],
      },
      {
        x: 87,
        z: 32,
        width: 14,
        depth: 8,
        trees: [
          { x: 84, z: 31, size: 3.8 },
          { x: 90, z: 33, size: 3.3 },
        ],
      },
    ],
  },
};
