// Authored neighborhood plans: activity counts never move streets or buildings.
const site = (
  id,
  role,
  x,
  z,
  roadZ,
  side,
  model,
  height,
  maxWidth,
  maxDepth,
  extra = {},
) => ({
  id,
  role,
  x,
  z,
  roadZ,
  side,
  model,
  height,
  maxWidth,
  maxDepth,
  ...extra,
});

export const DISTRICT_LAYOUTS = {
  1: {
    x: -60,
    z: 0,
    bounds: { left: -140, right: 20, top: -70, bottom: 70 },
    polygon: [
      { x: -126.727, z: -62.601 },
      { x: -119.185, z: -68.025 },
      { x: -110.012, z: -69.501 },
      { x: -7.99, z: -64.4 },
      { x: -0.652, z: -62.62 },
      { x: 5.381, z: -58.08 },
      { x: 13.273, z: -49.399 },
      { x: 18.318, z: -41.35 },
      { x: 20.0, z: -32.0 },
      { x: 20.0, z: 43.0 },
      { x: 18.259, z: 51.175 },
      { x: 13.034, z: 57.699 },
      { x: 4.966, z: 64.301 },
      { x: -2.507, z: 68.499 },
      { x: -10.995, z: 69.695 },
      { x: -113.004, z: 66.237 },
      { x: -119.552, z: 64.889 },
      { x: -125.203, z: 61.317 },
      { x: -134.054, z: 53.352 },
      { x: -138.513, z: 47.338 },
      { x: -140.0, z: 40.0 },
      { x: -140.0, z: -38.0 },
      { x: -138.318, z: -47.35 },
      { x: -133.273, z: -55.399 },
    ],
    roadZ: 0,
    loop: { left: -122, right: 2, top: -42, bottom: 54 },
    localRoads: [
      [-122, -42, 2, -42],
      [-122, 0, 20, 0],
      [-122, 54, 2, 54],
      [-122, -42, -122, 54],
      [-60, -42, -60, 54],
      [2, -42, 2, 54],
      [-60, 28, 2, 28],
    ],
    localTour: [
      { x: -122, z: 0 },
      { x: -122, z: -42 },
      { x: 2, z: -42 },
      { x: 2, z: 54 },
      { x: -122, z: 54 },
      { x: -122, z: 0 },
    ],
    gate: { x: 20, z: 0, side: "east", outward: { x: 1, z: 0 } },
    bay: { x: 15, z: -9 },
    walkBay: { x: 15, z: -13 },
    station: { x: -76, z: 42, stairDirection: -1 },
    sites: [
      site(
        "eth-finance",
        "integrator",
        -104,
        -56,
        -42,
        -1,
        "building-skyscraper-b",
        28,
        10,
        10,
        { slot: 0 },
      ),
      site(
        "eth-exchange",
        "integrator",
        -16,
        -55,
        -42,
        -1,
        "building-skyscraper-c",
        24,
        9,
        9,
        { slot: 1 },
      ),
      site(
        "eth-market",
        "integrator",
        -104,
        -12.5,
        0,
        -1,
        "building-skyscraper-b",
        20,
        8,
        8,
        { slot: 2 },
      ),
      site(
        "eth-tower",
        "integrator",
        -16,
        -12.5,
        0,
        -1,
        "building-skyscraper-c",
        16,
        10,
        8,
        { slot: 3 },
      ),
      site(
        "eth-campus",
        "integrator",
        -16,
        15,
        28,
        -1,
        "building-g",
        12,
        9,
        8,
        { slot: 4 },
      ),
      site(
        "eth-home-origin",
        "relay",
        -106,
        14,
        0,
        1,
        "building-type-a",
        4.6,
        6,
        5.8,
        { endpoint: "origin", garage: false },
      ),
      site(
        "eth-home-destination",
        "relay",
        -42,
        16,
        28,
        -1,
        "building-type-c",
        4.1,
        6,
        5.8,
        { endpoint: "destination" },
      ),
      site(
        "eth-west-home",
        "relay",
        -87,
        -55,
        -42,
        -1,
        "building-type-b",
        3.8,
        6,
        5.8,
      ),
      site(
        "eth-garden-home",
        "relay",
        -72,
        -55,
        -42,
        -1,
        "building-type-a",
        4.4,
        6,
        5.8,
      ),
      site(
        "eth-north-home",
        "relay",
        -108,
        -27,
        -42,
        1,
        "building-type-c",
        4,
        6,
        5.8,
        { garage: false },
      ),
      site(
        "eth-east-home",
        "relay",
        -8,
        -27,
        -42,
        1,
        "building-type-b",
        3.7,
        6,
        5.8,
        { garage: false },
      ),
      site("eth-commons", "commons", -82, 14, 0, 1, "building-c", 5, 8, 6),
      site("eth-shop-row", "scenery", -94, -28, -42, 1, "building-h", 7, 8, 7),
      site(
        "eth-corner-shop",
        "scenery",
        -87,
        -10,
        0,
        -1,
        "building-e",
        5.5,
        9,
        6,
      ),
      site(
        "eth-office-row",
        "scenery",
        -72,
        -9.5,
        0,
        -1,
        "building-d",
        8,
        7,
        6,
      ),
      site(
        "eth-courtyard-home",
        "relay",
        -91,
        14,
        0,
        1,
        "building-type-c",
        4,
        6,
        5,
      ),
      site("eth-civic-block", "scenery", -72, 15, 0, 1, "building-f", 10, 7, 8),
      site(
        "eth-community-hall",
        "scenery",
        -79,
        30,
        54,
        -1,
        "building-j",
        8,
        19,
        11,
      ),
      site(
        "eth-north-block",
        "scenery",
        -45,
        -54,
        -42,
        -1,
        "building-j",
        8,
        17,
        9,
      ),
      site(
        "eth-east-offices",
        "scenery",
        -46,
        -11,
        0,
        -1,
        "building-b",
        9,
        12,
        8,
      ),
      site(
        "eth-east-shops",
        "scenery",
        -31,
        -12,
        0,
        -1,
        "building-e",
        6,
        11,
        8,
      ),
      site(
        "eth-south-home-a",
        "relay",
        -108,
        63,
        54,
        1,
        "building-type-a",
        3,
        6,
        4,
        { garage: false },
      ),
      site(
        "eth-south-home-b",
        "relay",
        -89,
        63,
        54,
        1,
        "building-type-b",
        3,
        6,
        4,
        { garage: false },
      ),
      site(
        "eth-south-home-c",
        "relay",
        -40,
        63,
        54,
        1,
        "building-type-c",
        3,
        6,
        4,
        { garage: false },
      ),
      site("eth-police", "police", 13, 16, 0, 1, "building-a", 6.2, 5.5, 6),
      // Closely spaced north-side houses frame the financial skyline.
      site(
        "eth-north-west",
        "relay",
        -116,
        -55,
        -42,
        -1,
        "building-type-c",
        3.8,
        5.4,
        5.2,
        { garage: false },
      ),
      site(
        "eth-north-terrace",
        "relay",
        -95,
        -55,
        -42,
        -1,
        "building-type-a",
        3.8,
        5.4,
        5.2,
      ),
      site(
        "eth-north-garden",
        "relay",
        -80,
        -55,
        -42,
        -1,
        "building-type-c",
        3.9,
        5.4,
        5.2,
        { garage: false },
      ),
      site(
        "eth-north-corner",
        "relay",
        -61,
        -55,
        -42,
        -1,
        "building-type-b",
        3.8,
        5.4,
        5.2,
      ),
      site(
        "eth-north-east",
        "relay",
        -31,
        -55,
        -42,
        -1,
        "building-type-a",
        3.8,
        5.4,
        5.2,
        { garage: false },
      ),
      site(
        "eth-north-end",
        "relay",
        -6,
        -55,
        -42,
        -1,
        "building-type-c",
        3.8,
        5.2,
        5.2,
      ),
      // Interior infill leaves the street, terminal apron and pocket gardens clear.
      site(
        "eth-garden-court",
        "relay",
        -48,
        -28,
        -42,
        1,
        "building-type-c",
        3.8,
        5.2,
        5.2,
      ),
      site(
        "eth-east-court",
        "relay",
        -18,
        -28,
        -42,
        1,
        "building-type-a",
        3.6,
        5.2,
        5.2,
      ),
      site(
        "eth-west-mews",
        "relay",
        -113,
        -14,
        0,
        -1,
        "building-type-c",
        3.8,
        5.2,
        5.2,
        { garage: false },
      ),
      site(
        "eth-west-court",
        "relay",
        -113,
        15,
        0,
        1,
        "building-type-b",
        3.5,
        5.2,
        5.2,
        { garage: false },
      ),
      site(
        "eth-central-mews",
        "relay",
        -50,
        15,
        28,
        -1,
        "building-type-c",
        3.8,
        5.2,
        5.2,
        { garage: false },
      ),
      site(
        "eth-east-mews",
        "relay",
        -29,
        15,
        28,
        -1,
        "building-type-b",
        3.7,
        5.4,
        5.2,
      ),
      site(
        "eth-park-shop",
        "scenery",
        -91,
        29,
        0,
        1,
        "building-d",
        6.1,
        4.8,
        5.2,
      ),
      // A tight southern terrace backs onto the viaduct without blocking it.
      site(
        "eth-south-terrace-a",
        "relay",
        -99,
        63,
        54,
        1,
        "building-type-c",
        3.2,
        5.2,
        4,
        { garage: false },
      ),
      site(
        "eth-south-terrace-b",
        "relay",
        -80,
        63,
        54,
        1,
        "building-type-a",
        3.2,
        5.2,
        4,
        { garage: false },
      ),
      site(
        "eth-south-terrace-c",
        "relay",
        -71,
        63,
        54,
        1,
        "building-type-c",
        3.2,
        5.2,
        4,
        { garage: false },
      ),
      site(
        "eth-south-terrace-d",
        "relay",
        -61,
        64.5,
        54,
        1,
        "building-type-b",
        3.2,
        5.2,
        4,
      ),
      site(
        "eth-south-terrace-e",
        "relay",
        -51,
        65,
        54,
        1,
        "building-type-c",
        3.2,
        5.2,
        4,
      ),
      site(
        "eth-south-terrace-f",
        "relay",
        -30,
        65,
        54,
        1,
        "building-type-a",
        3.2,
        5.2,
        4,
      ),
      site(
        "eth-south-terrace-g",
        "relay",
        -21,
        65,
        54,
        1,
        "building-type-c",
        3.2,
        5.2,
        4,
      ),
      site(
        "eth-south-terrace-h",
        "relay",
        -12,
        65,
        54,
        1,
        "building-type-b",
        3.2,
        5.2,
        4,
        { garage: false },
      ),
      site(
        "eth-south-terrace-i",
        "relay",
        -116,
        63,
        54,
        1,
        "building-type-c",
        2.9,
        4.6,
        3.5,
        { garage: false },
      ),
      site(
        "eth-east-apartments",
        "scenery",
        13,
        -29,
        -42,
        1,
        "building-f",
        8,
        5.4,
        6,
      ),
      site(
        "eth-east-corner-block",
        "scenery",
        13,
        32,
        28,
        1,
        "building-b",
        7.4,
        5.4,
        5.4,
      ),
      site(
        "eth-west-apartments",
        "scenery",
        -133,
        -27,
        -42,
        1,
        "building-f",
        8.6,
        5.4,
        6,
      ),
      site(
        "eth-west-studios",
        "scenery",
        -133,
        15,
        0,
        1,
        "building-h",
        6.6,
        5.4,
        6,
      ),
      site(
        "eth-bus-terminal",
        "bus-terminal",
        -78,
        -26,
        0,
        -1,
        "building-j",
        6.5,
        12,
        9,
      ),
    ],
    parks: [
      {
        x: -133,
        z: -6,
        width: 7,
        depth: 16,
        trees: [
          { x: -133, z: -11, size: 4.3 },
          { x: -132, z: -3, size: 3.8 },
        ],
      },
      {
        x: -106,
        z: 30,
        width: 20,
        depth: 12,
        trees: [
          { x: -113, z: 29, size: 3.7 },
          { x: -99, z: 31, size: 4.2 },
        ],
      },
      {
        x: -53,
        z: -57,
        width: 3,
        depth: 8,
        trees: [
          { x: -53, z: -58, size: 4.1 },
          { x: -53, z: -54, size: 3.3 },
        ],
      },
      {
        x: -66,
        z: 63,
        width: 3,
        depth: 5,
        trees: [{ x: -66, z: 63, size: 3.6 }],
      },
      {
        x: -36,
        z: 15,
        width: 3,
        depth: 8,
        trees: [
          { x: -36, z: 12, size: 3.8 },
          { x: -36, z: 17, size: 3.3 },
        ],
      },
      {
        x: -102,
        z: -34.5,
        width: 4,
        depth: 2.6,
        trees: [{ x: -102, z: -35, size: 3.4 }],
      },
      {
        x: -47,
        z: 36,
        width: 12,
        depth: 3,
        trees: [
          { x: -51, z: 36, size: 3.4 },
          { x: -44, z: 36, size: 3.6 },
        ],
      },
      {
        x: -18,
        z: 36,
        width: 12,
        depth: 3,
        trees: [
          { x: -22, z: 36, size: 3.5 },
          { x: -15, z: 36, size: 3.1 },
        ],
      },
      {
        x: -99,
        z: 22,
        width: 10,
        depth: 2.8,
        trees: [
          { x: -102, z: 22, size: 3.4 },
          { x: -96, z: 22, size: 3.2 },
        ],
      },
      {
        x: -33,
        z: -28,
        width: 12,
        depth: 13,
        trees: [
          { x: -35, z: -31, size: 4.1 },
          { x: -29, z: -25, size: 3.6 },
        ],
      },
    ],
  },
  8453: {
    x: 109,
    z: 0,
    bounds: { left: 68, right: 150, top: -36, bottom: 54 },
    polygon: [
      { x: 75.439, z: -32.927 },
      { x: 78.36, z: -35.232 },
      { x: 82.0, z: -36.0 },
      { x: 132.0, z: -36.0 },
      { x: 136.669, z: -35.152 },
      { x: 140.674, z: -32.609 },
      { x: 146.326, z: -27.391 },
      { x: 149.081, z: -23.598 },
      { x: 150.0, z: -19.0 },
      { x: 150.0, z: 34.0 },
      { x: 148.939, z: 39.561 },
      { x: 145.757, z: 44.243 },
      { x: 140.243, z: 49.757 },
      { x: 135.561, z: 52.939 },
      { x: 130.0, z: 54.0 },
      { x: 85.0, z: 54.0 },
      { x: 80.469, z: 53.024 },
      { x: 76.877, z: 50.096 },
      { x: 71.123, z: 42.904 },
      { x: 68.781, z: 38.726 },
      { x: 68.0, z: 34.0 },
      { x: 68.0, z: -20.0 },
      { x: 68.64, z: -23.768 },
      { x: 70.561, z: -27.073 },
    ],
    roadZ: 0,
    loop: { left: 80, right: 138, top: -20, bottom: 12 },
    localRoads: [
      [80, -20, 138, -20],
      [80, 12, 138, 12],
      [80, -20, 80, 12],
      [138, -20, 138, 12],
      [68, 0, 109, 0],
      [109, -20, 109, 0],
    ],
    localTour: [
      { x: 80, z: 0 },
      { x: 80, z: -20 },
      { x: 138, z: -20 },
      { x: 138, z: 12 },
      { x: 80, z: 12 },
      { x: 80, z: 0 },
    ],
    gate: { x: 68, z: 0, side: "west", outward: { x: -1, z: 0 } },
    bay: { x: 73, z: -9 },
    walkBay: { x: 73, z: -13 },
    station: { x: 109, z: 42, stairDirection: 1 },
    sites: [
      site(
        "base-workshop",
        "integrator",
        123,
        -31.3,
        -20,
        -1,
        "building-i",
        7,
        9,
        6,
        { slot: 0 },
      ),
      site(
        "base-home-origin",
        "relay",
        94,
        -11.3,
        0,
        -1,
        "building-type-b",
        3.7,
        5.8,
        5.4,
        { endpoint: "origin", garage: false },
      ),
      site(
        "base-home-destination",
        "relay",
        120,
        24,
        12,
        1,
        "building-type-c",
        4.2,
        6,
        5.6,
        { endpoint: "destination" },
      ),
      site(
        "base-garden-home",
        "relay",
        89,
        24,
        12,
        1,
        "building-type-a",
        3.8,
        6,
        5.6,
        { garage: false },
      ),
      site(
        "base-commons",
        "commons",
        91,
        -31.3,
        -20,
        -1,
        "building-c",
        4.3,
        7,
        6,
      ),
      site("base-police", "police", 133, 24, 12, 1, "building-a", 5.8, 5.5, 6),
      site(
        "base-bus-terminal",
        "bus-terminal",
        106,
        30,
        12,
        1,
        "building-j",
        6.5,
        12,
        8,
      ),
    ],
    parks: [
      {
        x: 126,
        z: -5,
        width: 12,
        depth: 11,
        trees: [
          { x: 122, z: -5, size: 3.2 },
          { x: 130, z: -4, size: 3.8 },
        ],
      },
      {
        x: 87,
        z: 32,
        width: 14,
        depth: 8,
        trees: [
          { x: 84, z: 31, size: 3.8 },
          { x: 90, z: 33, size: 3.3 },
        ],
      },
    ],
  },
};
